name: Test Docker Hub Images

on: [push]
  
jobs:
  centos7:
    runs-on: ubuntu-18.04
    container: docker://nasatrick/trick_centos7:latest
    steps:
      - name: run tests
        run: |
          cd /trick*
          make test
  
  centos8:
    runs-on: ubuntu-18.04
    container: docker://nasatrick/trick_centos8:latest
    steps:
      - name: run tests
        run: |
          cd /trick*
          make test
                   
  ubuntu1804:
    runs-on: ubuntu-18.04
    container: docker://nasatrick/trick_ubuntu1804:latest
    steps:
      - name: run tests
        run: |
          cd /trick*
          make test  
